from pieces import *
from path_finding_actors import *


class Game:
    def __init__(self):
        self.wk = WhiteKing()
        self.wq = WhiteQueen()
        self.wb1 = WhiteBishop1()
        self.wb2 = WhiteBishop2()
        self.wn1 = WhiteKnight1()
        self.wn2 = WhiteKnight2()
        self.wr1 = WhiteRook1()
        self.wr2 = WhiteRook2()
        self.wp1 = WhitePawn1()
        self.wp2 = WhitePawn2()
        self.wp3 = WhitePawn3()
        self.wp4 = WhitePawn4()
        self.wp5 = WhitePawn5()
        self.wp6 = WhitePawn6()
        self.wp7 = WhitePawn7()
        self.wp8 = WhitePawn8()
        self.bk = BlackKing()
        self.bq = BlackQueen()
        self.bb1 = BlackBishop1()
        self.bb2 = BlackBishop2()
        self.bn1 = BlackKnight1()
        self.bn2 = BlackKnight2()
        self.br1 = BlackRook1()
        self.br2 = BlackRook2()
        self.bp1 = BlackPawn1()
        self.bp2 = BlackPawn2()
        self.bp3 = BlackPawn3()
        self.bp4 = BlackPawn4()
        self.bp5 = BlackPawn5()
        self.bp6 = BlackPawn6()
        self.bp7 = BlackPawn7()
        self.bp8 = BlackPawn8()

        self.pa1 = PathActor1(0, 0)
        self.pa2 = PathActor2(0, 1)
        self.pa3 = PathActor3(0, 2)
        self.pa4 = PathActor4(0, 3)
        self.pa5 = PathActor5(0, 4)
        self.pa6 = PathActor6(0, 5)
        self.pa7 = PathActor7(0, 6)
        self.pa8 = PathActor8(0, 7)
        self.pa9 = PathActor9(1, 0)
        self.pa10 = PathActor10(1, 1)
        self.pa11 = PathActor11(1, 2)
        self.pa12 = PathActor12(1, 3)
        self.pa13 = PathActor13(1, 4)
        self.pa14 = PathActor14(1, 5)
        self.pa15 = PathActor15(1, 6)
        self.pa16 = PathActor16(1, 7)
        self.pa17 = PathActor17(2, 0)
        self.pa18 = PathActor18(2, 1)
        self.pa19 = PathActor19(2, 2)
        self.pa20 = PathActor20(2, 3)
        self.pa21 = PathActor21(2, 4)
        self.pa22 = PathActor22(2, 5)
        self.pa23 = PathActor23(2, 6)
        self.pa24 = PathActor24(2, 7)
        self.pa25 = PathActor25(3, 0)
        self.pa26 = PathActor26(3, 1)
        self.pa27 = PathActor27(3, 2)
        self.pa28 = PathActor28(3, 3)
        self.pa29 = PathActor29(3, 4)
        self.pa30 = PathActor30(3, 5)
        self.pa31 = PathActor31(3, 6)
        self.pa32 = PathActor32(3, 7)
        self.pa33 = PathActor33(4, 0)
        self.pa34 = PathActor34(4, 1)
        self.pa35 = PathActor35(4, 2)
        self.pa36 = PathActor36(4, 3)
        self.pa37 = PathActor37(4, 4)
        self.pa38 = PathActor38(4, 5)
        self.pa39 = PathActor39(4, 6)
        self.pa40 = PathActor40(4, 7)
        self.pa41 = PathActor41(5, 0)
        self.pa42 = PathActor42(5, 1)
        self.pa43 = PathActor43(5, 2)
        self.pa44 = PathActor44(5, 3)
        self.pa45 = PathActor45(5, 4)
        self.pa46 = PathActor46(5, 5)
        self.pa47 = PathActor47(5, 6)
        self.pa48 = PathActor48(5, 7)
        self.pa49 = PathActor49(6, 0)
        self.pa50 = PathActor50(6, 1)
        self.pa51 = PathActor51(6, 2)
        self.pa52 = PathActor52(6, 3)
        self.pa53 = PathActor53(6, 4)
        self.pa54 = PathActor54(6, 5)
        self.pa55 = PathActor55(6, 6)
        self.pa56 = PathActor56(6, 7)
        self.pa57 = PathActor57(7, 0)
        self.pa58 = PathActor58(7, 1)
        self.pa59 = PathActor59(7, 2)
        self.pa60 = PathActor60(7, 3)
        self.pa61 = PathActor61(7, 4)
        self.pa62 = PathActor62(7, 5)
        self.pa63 = PathActor63(7, 6)
        self.pa64 = PathActor64(7, 7)

    def draw(self):
        self.wk.draw_piece()
        self.wq.draw_piece()
        self.wb1.draw_piece()
        self.wb2.draw_piece()
        self.wn1.draw_piece()
        self.wn2.draw_piece()
        self.wr1.draw_piece()
        self.wr2.draw_piece()
        self.wp1.draw_piece()
        self.wp2.draw_piece()
        self.wp3.draw_piece()
        self.wp4.draw_piece()
        self.wp5.draw_piece()
        self.wp6.draw_piece()
        self.wp7.draw_piece()
        self.wp8.draw_piece()
        self.bk.draw_piece()
        self.bq.draw_piece()
        self.bb1.draw_piece()
        self.bb2.draw_piece()
        self.bn1.draw_piece()
        self.bn2.draw_piece()
        self.br1.draw_piece()
        self.br2.draw_piece()
        self.bp1.draw_piece()
        self.bp2.draw_piece()
        self.bp3.draw_piece()
        self.bp4.draw_piece()
        self.bp5.draw_piece()
        self.bp6.draw_piece()
        self.bp7.draw_piece()
        self.bp8.draw_piece()

        self.pa1.draw_path()
        self.pa2.draw_path()
        self.pa3.draw_path()
        self.pa4.draw_path()
        self.pa5.draw_path()
        self.pa6.draw_path()
        self.pa7.draw_path()
        self.pa8.draw_path()
        self.pa9.draw_path()
        self.pa10.draw_path()
        self.pa11.draw_path()
        self.pa12.draw_path()
        self.pa13.draw_path()
        self.pa14.draw_path()
        self.pa15.draw_path()
        self.pa16.draw_path()
        self.pa17.draw_path()
        self.pa18.draw_path()
        self.pa19.draw_path()
        self.pa20.draw_path()
        self.pa21.draw_path()
        self.pa22.draw_path()
        self.pa23.draw_path()
        self.pa24.draw_path()
        self.pa25.draw_path()
        self.pa26.draw_path()
        self.pa27.draw_path()
        self.pa28.draw_path()
        self.pa29.draw_path()
        self.pa30.draw_path()
        self.pa31.draw_path()
        self.pa32.draw_path()
        self.pa33.draw_path()
        self.pa34.draw_path()
        self.pa35.draw_path()
        self.pa36.draw_path()
        self.pa37.draw_path()
        self.pa38.draw_path()
        self.pa39.draw_path()
        self.pa40.draw_path()
        self.pa41.draw_path()
        self.pa42.draw_path()
        self.pa43.draw_path()
        self.pa44.draw_path()
        self.pa45.draw_path()
        self.pa46.draw_path()
        self.pa47.draw_path()
        self.pa48.draw_path()
        self.pa49.draw_path()
        self.pa50.draw_path()
        self.pa51.draw_path()
        self.pa52.draw_path()
        self.pa53.draw_path()
        self.pa54.draw_path()
        self.pa55.draw_path()
        self.pa56.draw_path()
        self.pa57.draw_path()
        self.pa58.draw_path()
        self.pa59.draw_path()
        self.pa60.draw_path()
        self.pa61.draw_path()
        self.pa62.draw_path()
        self.pa63.draw_path()
        self.pa64.draw_path()

    def update(self):
        self.wk.update_piece()
        self.wq.update_piece()
        self.wb1.update_piece()
        self.wb2.update_piece()
        self.wn1.update_piece()
        self.wn2.update_piece()
        self.wr1.update_piece()
        self.wr2.update_piece()
        self.wp1.update_piece()
        self.wp2.update_piece()
        self.wp3.update_piece()
        self.wp4.update_piece()
        self.wp5.update_piece()
        self.wp6.update_piece()
        self.wp7.update_piece()
        self.wp8.update_piece()
        self.bk.update_piece()
        self.bq.update_piece()
        self.bb1.update_piece()
        self.bb2.update_piece()
        self.bn1.update_piece()
        self.bn2.update_piece()
        self.br1.update_piece()
        self.br2.update_piece()
        self.bp1.update_piece()
        self.bp2.update_piece()
        self.bp3.update_piece()
        self.bp4.update_piece()
        self.bp5.update_piece()
        self.bp6.update_piece()
        self.bp7.update_piece()
        self.bp8.update_piece()

        self.pa1.update_path()
        self.pa2.update_path()
        self.pa3.update_path()
        self.pa4.update_path()
        self.pa5.update_path()
        self.pa6.update_path()
        self.pa7.update_path()
        self.pa8.update_path()
        self.pa9.update_path()
        self.pa10.update_path()
        self.pa11.update_path()
        self.pa12.update_path()
        self.pa13.update_path()
        self.pa14.update_path()
        self.pa15.update_path()
        self.pa16.update_path()
        self.pa17.update_path()
        self.pa18.update_path()
        self.pa19.update_path()
        self.pa20.update_path()
        self.pa21.update_path()
        self.pa22.update_path()
        self.pa23.update_path()
        self.pa24.update_path()
        self.pa25.update_path()
        self.pa26.update_path()
        self.pa27.update_path()
        self.pa28.update_path()
        self.pa29.update_path()
        self.pa30.update_path()
        self.pa31.update_path()
        self.pa32.update_path()
        self.pa33.update_path()
        self.pa34.update_path()
        self.pa35.update_path()
        self.pa36.update_path()
        self.pa37.update_path()
        self.pa38.update_path()
        self.pa39.update_path()
        self.pa40.update_path()
        self.pa41.update_path()
        self.pa42.update_path()
        self.pa43.update_path()
        self.pa44.update_path()
        self.pa45.update_path()
        self.pa46.update_path()
        self.pa47.update_path()
        self.pa48.update_path()
        self.pa49.update_path()
        self.pa50.update_path()
        self.pa51.update_path()
        self.pa52.update_path()
        self.pa53.update_path()
        self.pa54.update_path()
        self.pa55.update_path()
        self.pa56.update_path()
        self.pa57.update_path()
        self.pa58.update_path()
        self.pa59.update_path()
        self.pa60.update_path()
        self.pa61.update_path()
        self.pa62.update_path()
        self.pa63.update_path()
        self.pa64.update_path()

    def check_mouse_down(self, pos):
        self.wk.check_click(pos)
        self.wq.check_click(pos)
        self.wb1.check_click(pos)
        self.wb2.check_click(pos)
        self.wn1.check_click(pos)
        self.wn2.check_click(pos)
        self.wr1.check_click(pos)
        self.wr2.check_click(pos)
        self.wp1.check_click(pos)
        self.wp2.check_click(pos)
        self.wp3.check_click(pos)
        self.wp4.check_click(pos)
        self.wp5.check_click(pos)
        self.wp6.check_click(pos)
        self.wp7.check_click(pos)
        self.wp8.check_click(pos)
        self.bk.check_click(pos)
        self.bq.check_click(pos)
        self.bb1.check_click(pos)
        self.bb2.check_click(pos)
        self.bn1.check_click(pos)
        self.bn2.check_click(pos)
        self.br1.check_click(pos)
        self.br2.check_click(pos)
        self.bp1.check_click(pos)
        self.bp2.check_click(pos)
        self.bp3.check_click(pos)
        self.bp4.check_click(pos)
        self.bp5.check_click(pos)
        self.bp6.check_click(pos)
        self.bp7.check_click(pos)
        self.bp8.check_click(pos)